inherit_gem:
  rubocop-rootstrap:
    - config/default_edge.yml

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/rsgem/gem.rb
    - lib/rsgem/tasks/output.rb
